services:
    next-app:
        container_name: next-app
        build: ./dockerfile
        ports:
            - 8080:3000
        env_file: ./.env
        environment:
            - NODE_ENV=development
            - DATABASE_URL=${DB_URL}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./app:/app
        restart: unless-stopped
        command: sh ./run-server.sh

    db:
        image: postgres
        container_name: postgres_db
        env_file:
            - ./.env
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"
