name: Auto Tag (package.json)

on:
    push:
        branches:
            - main

jobs:
    autotag:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Read version from package.json
              id: get_version
              run: echo "VERSION=v$(jq -r .version package.json)" >> $GITHUB_ENV

            - name: Create tag
              run: |
                  if git rev-parse $VERSION >/dev/null 2>&1; then
                    echo "⚠️ Тег $VERSION уже существует, пропускаем."
                  else
                    git tag $VERSION
                    git push origin $VERSION
                  fi
